import './global.scss';
import UserProfile from "@/components/UserProfile/UserProfile";
import { ProfileModalProvider } from "@/app/_providers/ProfileModalContext";
import { ActiveChatProvider } from "@/app/_providers/ActiveChatContext";

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ActiveChatProvider>
          <ProfileModalProvider>
            {children}
            <UserProfile />
          </ProfileModalProvider>
        </ActiveChatProvider>
      </body>
    </html>
  );
}
